services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  prometheus:
    image: 'prom/prometheus:latest'
    ports:
      - '9090:9090'
    volumes:
      - ./dockerfiles/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: 'grafana/grafana:latest'
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - ./dockerfiles/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
      - ./dockerfiles/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yml
      - ./dockerfiles/grafana-dashboard.json:/etc/grafana/dashboards/grafana-dashboard.json
