spring:
  main:
    lazy-initialization: true
  rsocket:
    server:
      port: 7000
      address: localhost
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    io.rsocket: DEBUG
