spring:
  main:
    lazy-initialization: true
  rsocket:
    server:
      port: 7000
      address: localhost
      transport: tcp
#      transport: websocket
#      mapping-path: /ws
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    io.rsocket: DEBUG

server:
  port: 8080
  compression:
    enabled: true

micrometer:
  prometheus-proxy:
    tcp-port: 7000
