

spring:
  main:
    lazy-initialization: true
  rsocket:
    server:
      port: 7000
      address: localhost
      transport: tcp
#      transport: websocket
#      mapping-path: /ws
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    io.rsocket: DEBUG

management:
  metrics:
    export:
      prometheus:
        rsocket:
          host: localhost
          port: 7000
          max-retries: 1000
          first-backoff: 10s
          max-backoff: 10m
          transport: tcp
server:
  compression:
    enabled: true
