spring:
  main:
    lazy-initialization: true
  rsocket:
    server:
      port: 7000
      address: 127.0.0.1
      transport: tcp
#      transport: websocket
#      mapping-path: /ws
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    io.rsocket: DEBUG

server:
  compression:
    enabled: true
